### PR TITLE
Add k8s

### PR DESCRIPTION
**Pull request by amerkul**

### CODE REVIEW

**Comment by h1alexbel** [comment]
@amerkul ok, but i don't see any ```script``` to run an app on K8s.

**Comment by amerkul** [comment]
@h1alexbel  I'm lazy. Sorry... I will add it as soon as possible.

**Comment by h1alexbel** [comment]
> @h1alexbel I'm lazy. Sorry... I will add it as soon as possible.

@amerkul ok

**Comment by amerkul** [comment]
Done

**Review by h1alexbel — APPROVED** [review]

**Pull request merged**
